version: 2

project_name: filebrowser

env:
  - GO111MODULE=on

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/filebrowser/filebrowser/v2/version.Version={{ .Version }} -X github.com/filebrowser/filebrowser/v2/version.CommitSHA={{ .ShortCommit }}
    main: main.go
    binary: filebrowser
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
      - riscv64
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: freebsd
        goarch: arm

archives:
  - name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]

dockers:
  # Alpine docker images
  - dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "the-lemonboy/filebrowser:{{ .Tag }}-amd64"
      - "the-lemonboy/filebrowser:v{{ .Major }}-amd64"
    extra_files:
      - docker
  - dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    image_templates:
      - "the-lemonboy/filebrowser:{{ .Tag }}-arm64"
      - "the-lemonboy/filebrowser:v{{ .Major }}-arm64"
    extra_files:
      - docker
  - dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v6"
    goos: linux
    goarch: arm
    goarm: "6"
    image_templates:
      - "the-lemonboy/filebrowser:{{ .Tag }}-armv6"
      - "the-lemonboy/filebrowser:v{{ .Major }}-armv6"
    extra_files:
      - docker
  - dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v7"
    goos: linux
    goarch: arm
    goarm: "7"
    image_templates:
      - "the-lemonboy/filebrowser:{{ .Tag }}-armv7"
      - "the-lemonboy/filebrowser:v{{ .Major }}-armv7"
    extra_files:
      - docker

  ## s6-overlay docker images
  - dockerfile: Dockerfile.s6
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "the-lemonboy/filebrowser:{{ .Tag }}-amd64-s6"
      - "the-lemonboy/filebrowser:v{{ .Major }}-amd64-s6"
    extra_files:
      - docker
  - dockerfile: Dockerfile.s6
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    image_templates:
      - "the-lemonboy/filebrowser:{{ .Tag }}-arm64-s6"
      - "the-lemonboy/filebrowser:v{{ .Major }}-arm64-s6"
    extra_files:
      - docker

docker_manifests:
  - name_template: "the-lemonboy/filebrowser:latest"
    image_templates:
      - "the-lemonboy/filebrowser:{{ .Tag }}-amd64"
      - "the-lemonboy/filebrowser:{{ .Tag }}-arm64"
      - "the-lemonboy/filebrowser:{{ .Tag }}-armv7"
  - name_template: "the-lemonboy/filebrowser:{{ .Tag }}"
    image_templates:
      - "the-lemonboy/filebrowser:{{ .Tag }}-amd64"
      - "the-lemonboy/filebrowser:{{ .Tag }}-arm64"
      - "the-lemonboy/filebrowser:{{ .Tag }}-armv7"
  - name_template: "the-lemonboy/filebrowser:v{{ .Major }}"
    image_templates:
      - "the-lemonboy/filebrowser:v{{ .Major }}-amd64"
      - "the-lemonboy/filebrowser:v{{ .Major }}-arm64"
      - "the-lemonboy/filebrowser:v{{ .Major }}-armv7"
  ## s6 image manifests
  - name_template: "the-lemonboy/filebrowser:s6"
    image_templates:
      - "the-lemonboy/filebrowser:{{ .Tag }}-amd64-s6"
      - "the-lemonboy/filebrowser:{{ .Tag }}-arm64-s6"
  - name_template: "the-lemonboy/filebrowser:{{ .Tag }}-s6"
    image_templates:
      - "the-lemonboy/filebrowser:{{ .Tag }}-amd64-s6"
      - "the-lemonboy/filebrowser:{{ .Tag }}-arm64-s6"
  - name_template: "the-lemonboy/filebrowser:v{{ .Major }}-s6"
    image_templates:
      - "the-lemonboy/filebrowser:v{{ .Major }}-amd64-s6"
      - "the-lemonboy/filebrowser:v{{ .Major }}-arm64-s6"

homebrew_casks:
  - name: filebrowser
    repository:
      owner: filebrowser
      name: homebrew-tap
    commit_author:
      name: FileBrowser Robot
      email: robot@filebrowser.org
    homepage: https://github.com/the-lemonboy/filebrowser
    description: File Browser is a create-your-own-cloud-kind of software where you can install it on a server, direct it to a path and then access your files through a nice web interface
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/filebrowser"]
          end
